" Enable syntax highlighting
syntax on

if has('gui_running')
    set background=light
else
    set background=dark
endif

colorscheme solarized

" Enable line numbering (left margin)
" set number

set ruler

" Indentation settings
set shiftwidth=4
set softtabstop=4
set expandtab

" Tab display
highlight SpecialKey ctermfg=1
set list
set listchars=tab:T>

" treat all the *.rc files as NeoMutt configuration files
autocmd BufNewFile,BufRead *.rc set syntax=neomuttrc
