" Set the <Leader> key
let mapleader="\\"

" Enable syntax highlighting
syntax on

if has('gui_running')
    set background=light
else
    set background=dark
endif

colorscheme solarized

" Enable line numbering (left margin)
" set number

set ruler

" Indentation settings
set shiftwidth=4
set softtabstop=4
set expandtab

" Tab display
highlight SpecialKey ctermfg=1
set list
set listchars=tab:T>

" Toggle paste mode with F2
set pastetoggle=<F2>

" Remove control characters (except newline and tab) from the current buffer
function! SanitizeBuffer()
  silent! %s/[\x00-\x08\x0B-\x1F\x7F]//g

  " Remove ANSI/VT100 escape sequences
  silent! %s/\v\x1b\[[0-9;]*[A-Za-z]//g

  echo "Buffer sanitized"
endfunction

nnoremap <Leader>s :call SanitizeBuffer()<CR>

" treat all the *.rc files as NeoMutt configuration files
autocmd BufNewFile,BufRead *.rc set syntax=neomuttrc
