" Enable syntax highlighting
syntax on

if has('gui_running')
    set background=light
else
    set background=dark
endif

colorscheme solarized

" Enable line numbering (left margin)
" set number

" Indentation settings
set shiftwidth=4
set softtabstop=4
set expandtab
